fixes issue 145: Add sort key flag to topic
dokufreaks/plugin-tag pull request #203
Opened 2019-10-21 19:31 UTC by medmen

Issue 145 addresses a problem a came across recently:
topics are sorted "sortkey" and "sortorder" according to settings in plugin config. 
Changing this "on demand" might be favourable sometimes. 

In my case, default sorting in config is set to "title", but in a namespace called "news" i would like to sort by date with newest items first.
This patch lets you add the flags "sortkey" and "sortorder", preserving all other functionality: 

`{{topic>.?news&table&header&comments&sortkey=mdate&sortorder=descending}}`

2021-02-01 21:46 UTC, Klap-in commented on action.php
> +        $event->result = false;
I have not looked in detail how this event is working. But my first guess is that now all caches are affected. Are there no additional checks needed?

2021-02-01 22:08 UTC, Klap-in commented on action.php
> +        $event->result = false;
If I scan this https://www.dokuwiki.org/devel:event:parser_cache_use, I would expect the after event was used.

2021-02-01 22:41 UTC, Klap-in requested changes
Maybe I’m judging a bit to quick, but I think some parts are a shortcuts which need to be replaced by a robust approach. Further, I guess the current caching will affect everybody.

2021-02-01 22:41 UTC, Klap-in commented on syntax/topic.php
> +	global $conf, $my;
Why using global $my?

2021-02-01 22:41 UTC, Klap-in commented on syntax/topic.php
> +                $my->sort = $conf_val;
Is $my always defined at this point?

2021-02-01 22:41 UTC, Klap-in commented on syntax/topic.php
> +                $conf['plugin']['tag'][$conf_name] = $conf_val;
Why are conf settings (temporary)overwritten on the fly?

2021-02-02 10:25 UTC, michitux commented on action.php
> +        $event->result = false;
If the goal is to not to cache the HTML output of pages with this syntax, just call `nocache()` on the renderer. This is also done already in the old code, but maybe it is too far down in the code, I see some early returns before that which might prevent the cache from being purged in certain conditions.

2021-02-03 10:22 UTC, medmen commented on action.php
> +        $event->result = false;
Thanks for your hints. I will remove this again ASAP .

I hit a caching issue with 1 of my production dw sites that could only be resolved by appending purge=true to the page where sorting should take place. Adding this dirty hack made it work for me but was not intended for publishing ( dont push when you should be in bed already :) ) 

Interestingly this caching issue does not appear in other sites i tested - so far i don't what is wrong with that site ...

2021-02-03 10:23 UTC, medmen commented on syntax/topic.php
> +                $my->sort = $conf_val;
you are right, global $my is not needed and will be removed soon.

2021-02-03 10:32 UTC, medmen commented on syntax/topic.php
> +                $conf['plugin']['tag'][$conf_name] = $conf_val;
That is the only way i could figure out to make this work. I need a way to accept flags and pass them to helper.php (thats where sorting takes place). Since helper.php reads conf settings i figured overwriting them temporarily would be easiest. 
Before hogfather release i could manipulate the plugin's config only (no global needed), but this throws an error nowadays.
Any cleaner solution is highly appreciated!

2021-02-04 12:50 UTC, michitux commented on syntax/topic.php
> +                $conf['plugin']['tag'][$conf_name] = $conf_val;
You could just add a parameter for flags to the helper method. Just make sure that it is optional such that existing code can still use the method without it. You could have a look at the [include plugin](https://github.com/dokufreaks/plugin-include/blob/master/helper.php) how a flags array could look like. The code is not the most beautiful or modern PHP, but I think the general idea of a flags array with default values from the configuration should become clear.

2022-08-15 20:26 UTC, merged